let a = 5;
let b = 10;
let sum = a + b;
let difference = a - b;
let product = a * b;
let quotient = a / b;
console.log("The sum of " + a + " and " + b + " is: " + sum);
console.log("The difference of " + a + " and " + b + " is: " + difference);
console.log("The product of " + a + " and " + b + " is: " + product);
console.log("The quotient of " + a + " and " + b + " is: " + quotient);
console.log("The sum of " + a + " and " + b + " is: " + sum);
console.log("The value of a is: " + a);
console.log("The value of b is: " + b); 
console.log("Hello, World!");